### ISSUE TITLE
Inconsistent variables differ from defaults

### ISSUE THREAD

**Issue by wavemoran** [spring-media/terraform-aws-lambda#46]
The `publish` variable defaults to `true` in the main module, https://github.com/spring-media/terraform-aws-lambda/blob/master/variables.tf#L60. However in the submodule, it defaults `false`, https://github.com/spring-media/terraform-aws-lambda/blob/master/modules/lambda/variables.tf#L43.

The docs indicate the default is false, https://www.terraform.io/docs/providers/aws/r/lambda_function.html#publish. Was there an intentional reason to set to `true`?

**Comment by moritzzimmer** [comment]
@wavemoran I wanted to model best practices we currently use here at spring-media inside the main module. 

The intention behind changing the  default for `publish` to `true` was to prevent people from blindly overriding the `latest` version of their lambdas (might also help using aliases). The submodule on the other hand reflects a Lambda function as defined in https://www.terraform.io/docs/providers/aws/r/lambda_function.html.

What are your thoughts? I see that it can be confusing (we also changed the `runtime` variable from required to default to `go1.x`).

**Comment by wavemoran** [comment]
It probably doesn't matter too much since the variable is called out and can be changed. It only caught me out because it was different than the default. I suppose most modules I've worked with, the TF provided defaults were usually expected.

**Comment by moritzzimmer** [comment]
will be set to default from https://www.terraform.io/docs/providers/aws/r/lambda_function.html in the next major version
