### ISSUE TITLE
Additional permissions

### ISSUE THREAD

**Issue by jaisingh** [spring-media/terraform-aws-lambda#54]
Allow for a new role or additional permissions be added to the role

**Comment by moritzzimmer** [comment]
@jaisingh `role_name` is exported, so you should be able to attach further policies to the created role (see https://github.com/spring-media/terraform-aws-lambda/blob/eac2f4f2a494fb3f3b806f8bc2698d2dc041e95e/modules/event/dynamodb/main.tf#L32 for example how we use this in an internal module).

Is this capability sufficient for your use case?

**Comment by jaisingh** [comment]
Thanks, that does indeed solve my issue. Appreciate the prompt response and thanks for the work on the module.
